name: docker

on:
  push:
  pull_request:
  release:

jobs:
  checks:

    runs-on: ubuntu-latest

    container:
      image: eddelbuettel/rocker-tiledb:${{ matrix.tag }}

    name: ${{ matrix.tag }}

    strategy:
      fail-fast: false
      matrix:
        include: [
          #{ tag: dev, valgrind: '--use-valgrind' },
          { tag: dev },
          { tag: dl },
          #{ tag: 1.7.7 },
          #{ tag: 2.0.8 },
          #{ tag: 2.1.6 },
          #{ tag: 2.2.9 },
          #{ tag: 2.3.4 },
          #{ tag: 2.4.3 },
          #{ tag: 2.5.4 },
          #{ tag: 2.6.4 },
          #{ tag: 2.7.2 },
          #{ tag: 2.8.2 },
          #{ tag: 2.9.5 },
          { tag: 2.10.4 },
          { tag: 2.11.3 },
          { tag: 2.12.2 },
          { tag: 2.13.1 },
          { tag: 2.14.2 },
          { tag: 2.15.4 },
          { tag: 2.16.3 },
          { tag: 2.17.4 },
          { tag: 2.18.3 },
          { tag: 2.19.2 },
          { tag: 2.20.1 },
          { tag: 2.21.2 },
          { tag: 2.22.0 },
          { tag: 2.23.0 }
        ]

    steps:
    - uses: actions/checkout@v4

    - name: Bootstrap
      run: r -p -e 'sessionInfo()'

    #- name: MaybePrune
    #  run: docker run --rm -i -v $(pwd):/mnt -w /mnt eddelbuettel/rocker-tiledb:${{ matrix.tag }} Rscript -e 'if (getRversion() < "4.1.0") unlink("inst/tinytest/test_tiledbarray_410.R")'

    - name: nanoarrow
      run: Rscript -e 'install.packages("nanoarrow")'

    - name: Build
      run: R CMD build --no-manual --no-build-vignettes .

    - name: Test
      run: R CMD check ${{matrix.valgrind}} --as-cran --no-manual --ignore-vignettes tiledb_*.tar.gz

    - name: Check Logs
      run: |
        cd tiledb.Rcheck/tests
        for file in tinytest.Rout tinytest.Rout.fail; do
            if test -f ${file}; then
                cat ${file}
            fi
        done
