name: docker
on: [push, pull_request]
jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: dev
            tag: dev
            valgrind: '--use-valgrind'
          - name: dl
            tag: dl
          #- name: 1.7.7
          #  tag: 1.7.7
          - name: 2.0.8
            tag: 2.0.8
          - name: 2.1.6
            tag: 2.1.6
          - name: 2.2.9
            tag: 2.2.9
          - name: 2.3.4
            tag: 2.3.4
          - name: 2.4.3
            tag: 2.4.3
          - name: 2.5.2
            tag: 2.5.2
            valgrind: '--use-valgrind'

    steps:
    - uses: actions/checkout@v2
    - name: Bootstrap
      run: |
        docker pull eddelbuettel/rocker-tiledb:${{ matrix.tag }}
        docker run --rm -i -v $(pwd):/mnt -w /mnt eddelbuettel/rocker-tiledb:${{ matrix.tag }} r -p -e 'sessionInfo()'
    #- name: MaybePrune
    #  run: docker run --rm -i -v $(pwd):/mnt -w /mnt eddelbuettel/rocker-tiledb:${{ matrix.tag }} Rscript -e 'if (getRversion() < "4.1.0") unlink("inst/tinytest/test_tiledbarray_410.R")'
    - name: Build
      run: docker run --rm -i -v $(pwd):/mnt -w /mnt eddelbuettel/rocker-tiledb:${{ matrix.tag }} R CMD build --no-manual --no-build-vignettes .
    - name: Test
      run: docker run --rm -i -v $(pwd):/mnt -w /mnt eddelbuettel/rocker-tiledb:${{ matrix.tag }} R CMD check ${{ matrix.valgrind }} --no-manual --no-vignettes tiledb_*.tar.gz
