name: docker
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: dev
            tag: dev
          - name: dl
            tag: dl
          - name: 2.1.3
            tag: 2.1.3
          - name: 2.0.8
            tag: 2.0.8
          - name: 1.7.7
            tag: 1.7.7
    steps:
    - uses: actions/checkout@v2
    - name: Bootstrap
      run: |
        docker pull eddelbuettel/rocker-tiledb:${{ matrix.tag }}
        docker run --rm -i -v $(pwd):/mnt -w /mnt eddelbuettel/rocker-tiledb:${{ matrix.tag }} r -p -e 'sessionInfo()'
    - name: Dependencies
      run: docker run --rm -i -v $(pwd):/mnt -w /mnt eddelbuettel/rocker-tiledb:${{ matrix.tag }} R CMD build --no-manual .
    - name: Test
      run: docker run --rm -i -v $(pwd):/mnt -w /mnt eddelbuettel/rocker-tiledb:${{ matrix.tag }} R CMD check --no-manual tiledb_*.tar.gz
