name: docker
on: [push, pull_request]
jobs:
  checks:
    runs-on: ubuntu-latest
    name: ${{ matrix.tag }}
    strategy:
      fail-fast: false
      matrix:
        include: [
          #{ tag: dev, valgrind: '--use-valgrind' },
          { tag: dev },
          { tag: dl },
          #{ tag: 1.7.7 },
          { tag: 2.0.8 },
          { tag: 2.1.6 },
          { tag: 2.2.9 },
          { tag: 2.3.4 },
          { tag: 2.4.3 },
          { tag: 2.5.4 },
          { tag: 2.6.3 },
          { tag: 2.7.1 },
          #{ tag: 2.7.0, valgrind: '--use-valgrind' }
        ]
    steps:
    - uses: actions/checkout@v2
    - name: Bootstrap
      run: |
        docker pull eddelbuettel/rocker-tiledb:${{ matrix.tag }}
        docker run --rm -i -v $(pwd):/mnt -w /mnt eddelbuettel/rocker-tiledb:${{ matrix.tag }} r -p -e 'sessionInfo()'
    #- name: MaybePrune
    #  run: docker run --rm -i -v $(pwd):/mnt -w /mnt eddelbuettel/rocker-tiledb:${{ matrix.tag }} Rscript -e 'if (getRversion() < "4.1.0") unlink("inst/tinytest/test_tiledbarray_410.R")'
    - name: Build
      run: docker run --rm -i -v $(pwd):/mnt -w /mnt eddelbuettel/rocker-tiledb:${{ matrix.tag }} R CMD build --no-manual --no-build-vignettes .
    - name: Test
      run: docker run --rm -i -v $(pwd):/mnt -w /mnt eddelbuettel/rocker-tiledb:${{ matrix.tag }} R CMD check ${{ matrix.valgrind }} --no-manual --no-vignettes tiledb_*.tar.gz
    - name: Check Logs
      run: |
        test -f tiledb.Rcheck/00check.log && cat tiledb.Rcheck/00check.log
        test -f tiledb.Rcheck/00check.log && cat tiledb.Rcheck/tests/tinytest.Rout
