name: docker

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    name: ${{ matrix.tag }}
    strategy:
      fail-fast: false
      matrix:
        include: [
          #{ tag: dev, valgrind: '--use-valgrind' },
          { tag: dev },
          { tag: dl },
          #{ tag: 1.7.7 },
          { tag: 2.0.8 },
          { tag: 2.1.6 },
          { tag: 2.2.9 },
          { tag: 2.3.4 },
          { tag: 2.4.3 },
          { tag: 2.5.4 },
          { tag: 2.6.4 },
          { tag: 2.7.2 },
          { tag: 2.8.2 },
          { tag: 2.9.5 }
        ]
    steps:
    - uses: actions/checkout@v2
    - name: Bootstrap
      run: |
        docker pull eddelbuettel/rocker-tiledb:${{ matrix.tag }}
        docker run --rm -i -v $(pwd):/mnt -w /mnt eddelbuettel/rocker-tiledb:${{ matrix.tag }} r -p -e 'sessionInfo()'
    #- name: MaybePrune
    #  run: docker run --rm -i -v $(pwd):/mnt -w /mnt eddelbuettel/rocker-tiledb:${{ matrix.tag }} Rscript -e 'if (getRversion() < "4.1.0") unlink("inst/tinytest/test_tiledbarray_410.R")'
    - name: Build
      run: docker run --rm -i -v $(pwd):/mnt -w /mnt eddelbuettel/rocker-tiledb:${{ matrix.tag }} R CMD build --no-manual --no-build-vignettes .
    - name: Test
      run: docker run --rm -i -v $(pwd):/mnt -w /mnt -e CI=true eddelbuettel/rocker-tiledb:${{ matrix.tag }} R CMD check ${{matrix.valgrind}} --as-cran --no-manual --ignore-vignettes tiledb_*.tar.gz
    - name: Check Logs
      run: |
        cd tiledb.Rcheck/tests
        for file in tinytest.Rout tinytest.Rout.fail; do
            if test -f ${file}; then
                cat ${file}
            fi
        done
