on:
  push:
  pull_request:

name: R-CMD-check

jobs:
  R-CMD-check:
    name: windows/mingw-w64
    runs-on: windows-latest
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install dependencies
        run: |
          setRepositories(ind = 1:2)
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
        env:
          R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_: false
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}

    name: docker/dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -name: Bootstrap
       run: |
         docker pull eddelbuettel/rocker-tiledb:dev
         docker run --rm -ti -v $(pwd):/mnt -w /mnt eddelbuettel/rocker-tiledb:dev r -p -e 'sessionInfo()'
      -name: Dependencies
       run: docker run --rm -ti -v $(pwd):/mnt -w /mnt eddelbuettel/rocker-tiledb:dev R CMD build --no-manual .
      -name: Test
       run: docker run --rm -ti -v $(pwd):/mnt -w /mnt eddelbuettel/rocker-tiledb:dev R CMD check --no-manual tiledb_*.tar.gz
