on:
  push:
  pull_request:
  release:
  workflow_dispatch:

name: windows

jobs:
  windows:
    runs-on: ${{ matrix.windows }}
    strategy:
      fail-fast: false
      matrix:
        include: [
          #{ windows: windows-latest, r: devel   },
          { windows: windows-latest, r: release }
        ]
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
        env:
          R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_: false
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--no-vignettes", "--as-cran"), build_args = c("--no-build-vignettes"), error_on = "error", check_dir = "check")
        shell: Rscript {0}
      - name: Show test log
        run: cat(readLines("D:/a/tldbr/tldbr/check/tiledb.Rcheck/00install.out"), "\n")
        if: failure()
        shell: Rscript {0}
